import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import RoomView from '../components/classroom/RoomView';
import { testRoom, testUser } from '../entities/TestEntities';
import styles from '../styles/pages/Home.module.css';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>NGVC</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<RoomView room={testRoom} user={testUser} />
		</>
	);
};

export default Home;
