import type { NextPage } from 'next';
import Head from 'next/head';
import RoomView from '../components/classroom/RoomView';
import { testRoom } from '../entities/TestEntities';
import { User } from '../entities/User';

const newUser = new User('Olivia Chang', 'olivia@example.com', '4');

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>{testRoom.name} - NGVC</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<RoomView room={testRoom} user={newUser} />
		</>
	);
};

export default Home;
