import { NextPage } from 'next';
import Head from 'next/head';
import { Login } from '../components/login/Login';

const LoginPage: NextPage = () => <>
	<Head>
		<title>Log in - NGVC</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
	</Head>
	<Login />
</>;

export default LoginPage;
