import type { NextPage } from 'next';
import Head from 'next/head';
import { ProfileView } from '../components/profile/Profile';
import { testRoomUser } from '../entities/TestEntities';

const Profile: NextPage = () =>
	<>
		<Head>
			<title>View profile - NGVC</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>

		<ProfileView user={testRoomUser} />
	</>;

export default Profile;